@WebApi_HostAddress = https://localhost:7055

POST {{WebApi_HostAddress}}/api/task
Content-Type: application/json

{
  "Name": "TestTask",
  "Deadline": "2025-01-01",
  "Description": "Test description",
  "TodoListId": 0
}

###

POST {{WebApi_HostAddress}}/api/taskcomment
Content-Type: application/json

{
  "Content": "Comment for task with 8 id",
  "TodoTaskId": 8
}

###

DELETE {{WebApi_HostAddress}}/api/task?id=8

###
