GET https://localhost:7055/api/TestAuth/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnaWdhbmlnYUBtYWlsLmNvbSIsImVtYWlsIjoiZ2lnYW5pZ2FAbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk1ZDQ5MTdmLThhNzctNDI1ZC1hNjc5LWE3Y2JmZWRmMWZlZSIsImp0aSI6Ijc2MTY2NDExLTg5M2QtNGJmOC1hNjc2LTdhZDYzNDg1M2MxMyIsImV4cCI6MTc2MDM5MDI3MCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo3MDU1IiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzE4OSJ9.BBr9oJ__XhqPywbJgWbCre9HEB4UvFJUPscdLr1HD3k
###